name: AUTO_LGTM

on:
  pull_request:
    types:
      - opened

jobs:
  looks_good_to_me_for_owner:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: LGTM Comment
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpenedReactions: "hooray, +1"
          pullRequestOpenedComment: LGTM
